//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranInfoManager.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.DataWebServiceSoap")]
    public interface DataWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TranInfoManager.ServiceReference.HelloWorldResponse HelloWorld(TranInfoManager.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TranInfoManager.ServiceReference.HelloWorldResponse> HelloWorldAsync(TranInfoManager.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userinfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        TranInfoManager.ServiceReference.GetInfoResponse GetInfo(TranInfoManager.ServiceReference.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TranInfoManager.ServiceReference.GetInfoResponse> GetInfoAsync(TranInfoManager.ServiceReference.GetInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 st 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMarket", ReplyAction="*")]
        TranInfoManager.ServiceReference.GetMarketResponse GetMarket(TranInfoManager.ServiceReference.GetMarketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMarket", ReplyAction="*")]
        System.Threading.Tasks.Task<TranInfoManager.ServiceReference.GetMarketResponse> GetMarketAsync(TranInfoManager.ServiceReference.GetMarketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TranInfoManager.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TranInfoManager.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TranInfoManager.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TranInfoManager.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfo", Namespace="http://tempuri.org/", Order=0)]
        public TranInfoManager.ServiceReference.GetInfoRequestBody Body;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(TranInfoManager.ServiceReference.GetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userinfo;
        
        public GetInfoRequestBody() {
        }
        
        public GetInfoRequestBody(string userinfo) {
            this.userinfo = userinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TranInfoManager.ServiceReference.GetInfoResponseBody Body;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(TranInfoManager.ServiceReference.GetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoResult;
        
        public GetInfoResponseBody() {
        }
        
        public GetInfoResponseBody(string GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMarketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMarket", Namespace="http://tempuri.org/", Order=0)]
        public TranInfoManager.ServiceReference.GetMarketRequestBody Body;
        
        public GetMarketRequest() {
        }
        
        public GetMarketRequest(TranInfoManager.ServiceReference.GetMarketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMarketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string st;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string et;
        
        public GetMarketRequestBody() {
        }
        
        public GetMarketRequestBody(string st, string et) {
            this.st = st;
            this.et = et;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMarketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMarketResponse", Namespace="http://tempuri.org/", Order=0)]
        public TranInfoManager.ServiceReference.GetMarketResponseBody Body;
        
        public GetMarketResponse() {
        }
        
        public GetMarketResponse(TranInfoManager.ServiceReference.GetMarketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMarketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMarketResult;
        
        public GetMarketResponseBody() {
        }
        
        public GetMarketResponseBody(string GetMarketResult) {
            this.GetMarketResult = GetMarketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataWebServiceSoapChannel : TranInfoManager.ServiceReference.DataWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataWebServiceSoapClient : System.ServiceModel.ClientBase<TranInfoManager.ServiceReference.DataWebServiceSoap>, TranInfoManager.ServiceReference.DataWebServiceSoap {
        
        public DataWebServiceSoapClient() {
        }
        
        public DataWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TranInfoManager.ServiceReference.HelloWorldResponse TranInfoManager.ServiceReference.DataWebServiceSoap.HelloWorld(TranInfoManager.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TranInfoManager.ServiceReference.HelloWorldRequest inValue = new TranInfoManager.ServiceReference.HelloWorldRequest();
            inValue.Body = new TranInfoManager.ServiceReference.HelloWorldRequestBody();
            TranInfoManager.ServiceReference.HelloWorldResponse retVal = ((TranInfoManager.ServiceReference.DataWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TranInfoManager.ServiceReference.HelloWorldResponse> TranInfoManager.ServiceReference.DataWebServiceSoap.HelloWorldAsync(TranInfoManager.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TranInfoManager.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            TranInfoManager.ServiceReference.HelloWorldRequest inValue = new TranInfoManager.ServiceReference.HelloWorldRequest();
            inValue.Body = new TranInfoManager.ServiceReference.HelloWorldRequestBody();
            return ((TranInfoManager.ServiceReference.DataWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TranInfoManager.ServiceReference.GetInfoResponse TranInfoManager.ServiceReference.DataWebServiceSoap.GetInfo(TranInfoManager.ServiceReference.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public string GetInfo(string userinfo) {
            TranInfoManager.ServiceReference.GetInfoRequest inValue = new TranInfoManager.ServiceReference.GetInfoRequest();
            inValue.Body = new TranInfoManager.ServiceReference.GetInfoRequestBody();
            inValue.Body.userinfo = userinfo;
            TranInfoManager.ServiceReference.GetInfoResponse retVal = ((TranInfoManager.ServiceReference.DataWebServiceSoap)(this)).GetInfo(inValue);
            return retVal.Body.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TranInfoManager.ServiceReference.GetInfoResponse> TranInfoManager.ServiceReference.DataWebServiceSoap.GetInfoAsync(TranInfoManager.ServiceReference.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TranInfoManager.ServiceReference.GetInfoResponse> GetInfoAsync(string userinfo) {
            TranInfoManager.ServiceReference.GetInfoRequest inValue = new TranInfoManager.ServiceReference.GetInfoRequest();
            inValue.Body = new TranInfoManager.ServiceReference.GetInfoRequestBody();
            inValue.Body.userinfo = userinfo;
            return ((TranInfoManager.ServiceReference.DataWebServiceSoap)(this)).GetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TranInfoManager.ServiceReference.GetMarketResponse TranInfoManager.ServiceReference.DataWebServiceSoap.GetMarket(TranInfoManager.ServiceReference.GetMarketRequest request) {
            return base.Channel.GetMarket(request);
        }
        
        public string GetMarket(string st, string et) {
            TranInfoManager.ServiceReference.GetMarketRequest inValue = new TranInfoManager.ServiceReference.GetMarketRequest();
            inValue.Body = new TranInfoManager.ServiceReference.GetMarketRequestBody();
            inValue.Body.st = st;
            inValue.Body.et = et;
            TranInfoManager.ServiceReference.GetMarketResponse retVal = ((TranInfoManager.ServiceReference.DataWebServiceSoap)(this)).GetMarket(inValue);
            return retVal.Body.GetMarketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TranInfoManager.ServiceReference.GetMarketResponse> TranInfoManager.ServiceReference.DataWebServiceSoap.GetMarketAsync(TranInfoManager.ServiceReference.GetMarketRequest request) {
            return base.Channel.GetMarketAsync(request);
        }
        
        public System.Threading.Tasks.Task<TranInfoManager.ServiceReference.GetMarketResponse> GetMarketAsync(string st, string et) {
            TranInfoManager.ServiceReference.GetMarketRequest inValue = new TranInfoManager.ServiceReference.GetMarketRequest();
            inValue.Body = new TranInfoManager.ServiceReference.GetMarketRequestBody();
            inValue.Body.st = st;
            inValue.Body.et = et;
            return ((TranInfoManager.ServiceReference.DataWebServiceSoap)(this)).GetMarketAsync(inValue);
        }
    }
}
